<?php echo $this->doctype(); ?>

<html class="no-js" lang="pt_BR">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Administração') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('bower_components/morrisjs/morris.css'))
        ->prependStylesheet($this->basePath('dist/css/sb-admin-2.css'))
        ->prependStylesheet($this->basePath('dist/css/timeline.css'))
        ->prependStylesheet($this->basePath('bower_components/metisMenu/dist/metisMenu.min.css'))
        ->prependStylesheet($this->basePath('css/jquery.dataTables.min.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>




</head>
<body>
<?php if($this->zfcUserIdentity()): ?>
<div id="wrapper">


        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">SGC - Sistema Gerenciador de Conteudo</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">

                <?php
                /**
                 * Configurações do Menu.
                 * Para Criar novos Menus deves editar o Arquivo config/autoload/global.php
                 * No Array Admin
                 */
                $partial = ['layout/navigation.phtml', 'default']; ?>
                <?php $this->navigation('admin_navigation')->menu()->setPartial($partial); ?>
                <?php echo $this->navigation('admin_navigation')->menu()->render(); ?>
                <li>
                    <a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Sair'); ?></a>
                </li>
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <?php
                        /**
                         * Configurações do Menu.
                         * Para Criar novos Menus deves editar o Arquivo config/autoload/global.php
                         * No Array Admin
                         */
                        $partial = ['layout/navigation.phtml', 'default']; ?>
                        <?php $this->navigation('admin_navigation')->menu()->setPartial($partial); ?>
                        <?php echo $this->navigation('admin_navigation')->menu()->render(); ?>

                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>


    <div id="page-wrapper">
        <?php echo ($this->zfcUserIdentity())? $this->zfcUserIdentity()->getEmail() : ""; ?>
        <?php echo $this->losNavigation()->breadcrumbs('admin_navigation')?>
        <?php echo $this->losflashmessenger()->renderAll()?>
        <?php echo $this->content; ?>

    </div>
    <!-- /#page-wrapper -->
    <?php else: ?>
            <?php echo ($this->zfcUserIdentity())? $this->zfcUserIdentity()->getEmail() : ""; ?>
            <?php echo $this->losNavigation()->breadcrumbs('admin_navigation')?>
            <?php echo $this->losflashmessenger()->renderAll()?>
            <?php echo $this->content; ?>


    <?php endif; ?>

</div>
<?php echo $this->inlineScript() ?>
<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath('dist/js/sb-admin-2.js'))
    ->prependFile($this->basePath('js/morris-data.js'))
    ->prependFile($this->basePath('bower_components/morrisjs/morris.min.js'))
    ->prependFile($this->basePath('bower_components/raphael/raphael-min.js'))
    ->prependFile($this->basePath('bower_components/metisMenu/dist/metisMenu.min.js'))
    ->prependFile($this->basePath('js/angular.min.js'))
    ->prependFile($this->basePath('js/script.js'))
    ->prependFile($this->basePath('js/bootstrap-typeahead.min.js'))
    ->prependFile($this->basePath('js/inputmask-plugin.js'))
    ->prependFile($this->basePath('js/jquery.dataTables.min.js'))
    ->prependFile($this->basePath('js/jquery.maskMoney.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
; ?>
</body>
</html>