<?php echo $this->doctype(); ?>

<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Administração') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->losHeadLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependBootstrap()
            ->appendFontAwesome()
            ->appendStylesheet($this->basePath() . '/css/style.css')
        ?>
        <?php /*echo $this->headLink()
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) */ ?>

        <!-- Scripts -->
        <?= $this->losHeadScript()
            ->prependBootstrap()
            ->prependJquery(); ?>

        <?= $this->headStyle() ?>
        <?php /*echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; */?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php echo $this->losNavigation()->menu('admin_navigation')?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->message(); ?><br>
            <?php echo $this->losNavigation()->breadcrumbs('admin_navigation')?>
            <?php echo $this->losflashmessenger()->renderAll()?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p class="zf-green">&copy; 2010 - <?php echo date('Y')?> <a href="http://www.sisdeve.com.br" target="_blank">Sisdeve - Sistema em Desenvolvimentos</a>. <?php echo $this->translate('All rights reserved.') ?></p>

            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
